name: online_store
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.5
  firebase_messaging: ^15.1.4
  provider: ^6.0.5
  carousel_slider: ^5.0.0
  another_carousel_pro: ^1.0.2
  smooth_page_indicator: ^1.2.0+3
  flutter_staggered_grid_view: ^0.7.0
  transparent_image: ^2.0.1
  alphabet_list_scroll_view: ^2.0.0
  faker: ^2.2.0
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.2
  curved_navigation_bar: ^1.0.6
  vibration: ^1.9.0
  image_picker: ^1.1.2
  flutter_plugin_android_lifecycle: ^2.0.1
  image_cropper: ^8.1.0

flutter_native_splash:
  image: "assets/images/logo.png"
  android: true
  ios: true
  web: false
  background_image: "assets/images/image_f.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/image_2.jpg
    - assets/images/logo.png
    - assets/images/icon_o.png
