// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO7jY0cgWWo67elhGty2v1enXzazbF5As',
    appId: '1:743393339744:android:9e6eabc8dab991606b5605',
    messagingSenderId: '743393339744',
    projectId: 'loja-virtual-bd179',
    storageBucket: 'loja-virtual-bd179.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXchi1aJ9JvOiyoT-nByDPZ61J1Fd5BBw',
    appId: '1:743393339744:ios:3bb7c4b7ce60cdd76b5605',
    messagingSenderId: '743393339744',
    projectId: 'loja-virtual-bd179',
    storageBucket: 'loja-virtual-bd179.firebasestorage.app',
    androidClientId: '743393339744-rvvkmbjkpsagd2s561okio2973e7u2ff.apps.googleusercontent.com',
    iosClientId: '743393339744-4qrtqki73pg2377no7imkksn42o81oqr.apps.googleusercontent.com',
    iosBundleId: 'com.malpha.onlineStore',
  );
}
